-- Run this once to set up the database used by config/database.php

CREATE DATABASE IF NOT EXISTS pwl_db
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_general_ci;

USE pwl_db;

CREATE TABLE IF NOT EXISTS products (
    id          CHAR(36) PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    price       DECIMAL(12,2) NOT NULL,
    description TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Optional sample data (UUIDs generated by MySQL just for these seed rows;
-- the app itself generates UUIDs in PHP via ramsey/uuid)
INSERT INTO products (id, name, price, description) VALUES
    (UUID(), 'Keyboard', 250000, 'Mechanical keyboard with blue switches'),
    (UUID(), 'Mouse', 120000, 'Wireless ergonomic mouse'),
    (UUID(), 'Monitor', 1750000, '24-inch IPS monitor, 75Hz');
